# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chicago Cannabis Alliance & Chicago Medical Cannabis Association
email: info@chicagocannabis.org
description: HELPING CHICAGO PATIENTS ACCESS THE CANNABIS MEDICINE THEY NEED
url: http://chicagocannabis.org # the base hostname & protocol for your site
#url: http://chicagocannabis.org # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
twitterUrl: http://www.google.com
facebookUrl: http://www.google.com
instagramUrl: http://www.google.com
googleMapsApiKey: AIzaSyCCGAjXuCpxKwqWc6kgkmCAv-ge2QnrQ1o
# Google services
google_analytics: UA-4628695-9

# Build settings
markdown: kramdown
